[package]
version = "0.1.0"
name = "recursive-program"
edition = "2021"

[dependencies]
sp1-zkvm = "1.1.0"
gnark-bn254-verifier = { git = "https://github.com/Bisht13/gnark-bn254-verifier", branch = "main" }
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
num-bigint = "0.4.6"